/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiff_androidvm_jni_JNI */

#ifndef _Included_com_jiff_androidvm_jni_JNI
#define _Included_com_jiff_androidvm_jni_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiff_androidvm_jni_JNI
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jiff_androidvm_jni_JNI_getString
  (JNIEnv *, jclass);

/*
 * Class:     com_jiff_androidvm_jni_JNI
 * Method:    startActivity
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jiff_androidvm_jni_JNI_startActivity
  (JNIEnv *, jclass);

/*
 * Class:     com_jiff_androidvm_jni_JNI
 * Method:    runExecutable
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_jiff_androidvm_jni_JNI_runExecutable
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
